config/routes.rb
Rails.application.routes.draw do

  devise_for :users
 root "welcome#index"

 get "welcome/about" => "welcome#about"

resources :posts do
  member do
    post 'upvote'
  end
end

resources :posts do
  member do
    post 'downvote'
  end
end

 resources :users do
  resources :posts
end

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  has_many :votes, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :photo,
                    styles: {
                              thumb: '100x100>',
                              square: '200x200#',
                              medium: '300x300>'
                            },
                    bucket: :blogrflynn

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  has_many :posts


  def to_s
    if self.name
      return self.name
    else
      return "Anonymous"
    end
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base

   belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

 def configure_permitted_parameters
    registration_params = [:email, :name, :password, :password_confirmation, :photo]
    devise_parameter_sanitizer.for(:sign_up) {
        |u| u.permit(registration_params)
      }
    devise_parameter_sanitizer.for(:account_update) {
        |u| u.permit(registration_params << :current_password)
      }

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @users = User.limit(10)
    @posts = @user.posts.order("updated_at DESC")
  end


  def show
    @post = Post.find(params[:id])
    @user = @post.user
  end


  def new
    @post = current_user.posts.new
  end


  def create
    @user = current_user
    @user.posts.create(safe_post_params)
    redirect_to user_posts_path(@user)
  end


  def edit
    @post = Post.find(params[:id])
  end


  def update
    @post = Post.find(params[:id])
    if @post.update(safe_post_params)
      redirect_to root_path
    else
      redirect_to edit_post_path
    end
  end


  def destroy
    Post.find(params[:id]).destroy
    redirect_to root_path
  end


  def upvote
    @post = Post.find(params[:id])
    @post.votes.create
    redirect_to :back
  end

  def downvote
    @post = Post.find(params[:id])
    @post.votes.first.destroy
    redirect_to :back
  end




  private

  def safe_post_params
    params.require(:post).permit(:title, :body)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @posts = Post.order("updated_at DESC")
    @users = User.limit(10)
  end

  def about

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_nav.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doggerel Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <a href="/"><%= image_tag 'logo-small.png', :class => "navbar_brand_logo" %></a>

        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to 'Home', root_path %></li>
        </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>

              <li><%= link_to 'About', welcome_about_path %></li>
              <li><%= link_to 'Profile', user_posts_path(current_user) %></li>

              <li><%= link_to "New Poem", new_user_post_path(current_user) %></li>

            <% else %>

              <li><%= link_to 'About', welcome_about_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>
              <li><%= link_to "Sign up", new_user_registration_path %></li>

            <% end %>

          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

app/views/layouts/application.html.erb
<%= render "layouts/nav" %>

<!--   <div class="container"> -s->

    <!-- <div class="row"> -->

      <!-- <div class="col-md-1">

      </div> -->

      <!-- <div class="col-md-12"> -->
        <%= yield %>
      <!-- </div> -->

      <!-- <div class="col-md-1">

      </div> -->

      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
 <!--    </div>end of first row -->

    <div class="row">

      <div class="col-md-2">

      </div>
      <div id="two" class="col-md-8">



      </div>
      <div class="col-md-2">

      </div>

    </div><!-- end of second row -->



  </div><!-- end of container -->
  <p id="copyright">&copy; 2016 Brian Danger Flynn</p>
</body>
</html>

app/views/posts/edit.html.erb
<div class="container">

  <h2>Edit poem by <%= current_user.name %></h2>

  <div>
    <%= form_for [current_user, @post] do |f| %>
    <p>Title:</p>
    <p><%= f.text_field :title %></p>
    <p>Body:</p>
    <p><%= f.text_area :body, size: "50x20" %></p>
    <%= f.submit "Update Poem", :class => "btn btn-default" %>
    <% end %>
  </div>

</div>

app/views/posts/index.html.erb
<div class="container">

  <div class="row">



<!-- profile pic -->

    <div class="col-md-3">

      <div class="profile_header">

        <%= image_tag @user.photo.url(:square), :class => "profile_pic" %>
         <h2><%= @user.name %></h2>
         <p>Number of posts: <%= @user.posts.count %></p>

 <% if @user.name == current_user.name %>

         <p><%= link_to 'Edit profile', edit_user_registration_path %></p>
          <p><%= link_to "Logout", destroy_user_session_path, method: :delete %></p>
<% end %>

      </div>
    </div>

<!-- profile pic -->



<!-- profile poems -->

    <div class="col-md-6">

<!--     <h3 id="profile_poems_header"><%= @user.name %>'s most recent poems:</h3> -->

        <% if @posts.count == 0 %>
         <article>
         <h3>No poems yet.</h3>
         </article>
       <% else %>

       <% @posts.each do |post| %>

        <article id="profile_poems">
          <h3><%= link_to post.title, user_post_path(@user, post) %></h3>

          <% if post.created_at > Time.now.beginning_of_day %>
          <h6><%="#{time_ago_in_words(post.created_at)} ago"%></h6>
          <% else %>
         <h6><%= post.created_at.strftime("%b %d, %Y") %></h6>
          <% end %>

          <p><%= simple_format(post.body) %></p>
          <p id="count"><%= pluralize(post.votes.count, "upvote") %></p>
          <span id="upvote"><%= link_to 'upvote +1', upvote_post_path(post), method: :post %></span>
          <span id="downvote"><%= link_to 'downvote', downvote_post_path(post), method: :post %></span>
        </article>

        <% end %>
      <% end %>
    </div>


<!-- profile poems -->



<!-- other poets -->

  <div id="profile_other_poets">
      <div class="col-md-3">

        <% if user_signed_in? %>
          <div id="user_list">

            <h4>More Poets:</h4>
            <% @users.each do |user| %>
              <div id="more_poets">
                <h5><%= link_to user.name, user_posts_path(user) %>&thinsp;&mdash;&thinsp;<%= user.posts.count %> poems</h5>
              </div>

            <% end %>

          </div>
        <% end %>

    </div>
  </div>
<!-- profile pic -->

  </div>
</div>

app/views/posts/new.html.erb
<div class="container">

  <h2>New poem by <%= current_user.name %></h2>

  <div>
    <%= form_for [current_user, @post] do |f| %>
    <p>Title:</p>
    <p><%= f.text_field :title %></p>
    <p>Body:</p>
    <p><%= f.text_area :body, size: "50x20" %></p>
    <%= f.submit "Add Poem", :class => "btn btn-default" %>
    <% end %>
  </div>

</div>

app/views/posts/show.html.erb
<div class="container">
  <article id="poem_show">
    <h2><%= @post.title %></h2>

    <h3>by <%= link_to @post.user.name, user_posts_path(@post.user) %></h3>

        <% if @post.created_at > Time.now.beginning_of_day %>
            <h6><%="#{time_ago_in_words(post.created_at)} ago"%></h6>
        <% else %>
            <h6><%= @post.created_at.strftime("%b %d, %Y") %></h6>
        <% end %>

    <p><%= simple_format(@post.body) %></p>

    <p id="count"><%= pluralize(@post.votes.count, "upvote") %></p>

    <span id="upvote"><%= link_to 'upvote +1', upvote_post_path(@post), method: :post %></span>
    <span id="downvote"><%= link_to 'downvote', downvote_post_path(@post), method: :post %></span>


    <% if @user.name == current_user.name %>
        <p id="edit_poem"><%= link_to "Edit Poem", edit_post_path %></p>

        <p id="delete_poem"><%= link_to "Delete Poem", @post, method: :delete, data: {confirm: "are you sure?"} %></p>
    <% end %>

  </article>
</div>

app/views/welcome/about.html.erb
<div class="container">
<article id="about_article">
  <h2 id="about_title">About Doggerel Blog</h2>

  <h3>What's this site about?</h3>

    <p>This is a forum for writing and sharing "bad" poetry.</p>

    <p>Uh.. Okay. Why?</p>

    <p>I miss the fun, light poetry I enjoyed as a child. The silly, irreverent rhyming ones. As I got older, teachers told me that those types of poems are bad and I stopped reading and writing them because I was ashamed. Then I got even older and kinda stopped caring.</p>

    <p>Doggerel Blog is dedicated to writing and sharing poems for fun, without caring whether or not other people think they're good.</p>

    <p>Whether you write badly, comedically, childishly or any variation of the three, we warmly welcome you to share your awful poetry on this site.</p>

  <h3>What's the deal with the weird name?</h3>

    <p>The word <strong>doggerel</strong> is an archaic term that literally means "bad poetry."</p>

    <p>It's derived from the Middle English "dogerel," which is probably a diminutive of "dog," and describes poetry that is irregular in rhythm and in rhyme, often deliberately for burlesque or comic effect.</p>

    <p>Appearing since ancient times in the literatures of many cultures, doggerel is characteristic of nursery rhymes and children's song. Less warmly, it's also used derisively to mean "verse or words that are badly written or expressed."</p>

  <h3>How should I use this site?</h3>
    <p>Use this site to goof off, blow off steam, warm up, practice, or brainstorm. It's intended to be fun and silly.</p>
    <p>Please don't use this site to bully or be intentionally hurtful or needlessly offensive. Just like, don't be a dick, you know?</p>


</article>
</div>

app/views/welcome/index.html.erb
<!-- logo start -->

  <div id="logo_div">
      <%= image_tag "doggerel-blog-logo.png", class: "main_logo" %>
  </div>

<!-- logo end -->


<div class="container">

<!-- row start -->

<div id="welcome_main" class="row">

<!-- current user dashboard -->
  <div class="col-md-3">
    <% if user_signed_in? %>
        <div id="user_dashboard">
        <h4>Your Profile:</h4>
          <%= image_tag current_user.photo.url, :class => "dashboard_pic" %>
          <h4><%= link_to current_user.name, user_posts_path(current_user) %></h4>
          <p>Number of posts: <%= current_user.posts.count %></p>
        </div>
    <% end %>
  </div>
<!-- current user dashboard end -->




<!-- poems -->
  <div class="col-md-6">
    <% if user_signed_in? %>
      <div id="new_poem"><%= link_to "Create New Poem", new_user_post_path(current_user) %></div>
    <% end %>

    <% @posts.each do |post| %>

    <article id="welcome_poems">
      <h3><%= post.title %></h3>

      <h4>By: <%= link_to post.user, user_posts_path(post.user) %></h4>

      <% if post.created_at > Time.now.beginning_of_day %>
          <h6><%="#{time_ago_in_words(post.created_at)} ago"%></h6>
      <% else %>
          <h6><%= post.created_at.strftime("%b %d, %Y") %></h6>
      <% end %>

      <p><%= simple_format(post.body) %></p>
      <p id="count"><%= pluralize(post.votes.count, "total votes") %></p>
      <span id="upvote"><%= link_to 'upvote +1', upvote_post_path(post), method: :post %></span>
      <span id="downvote"><%= link_to 'downvote', downvote_post_path(post), method: :post %></span>
    </article>

    <% end %>
  </div>
<!-- poems end -->




<!-- other users -->

  <div class="col-md-3">
  <% if user_signed_in? %>
    <div id="user_list">
    <h4>More Poets:</h4>
      <% @users.each do |user| %>
        <div id="more_poets">
          <h5><%= link_to user.name, user_posts_path(user) %>&thinsp;&mdash;&thinsp;<%= user.posts.count %> poems</h5>
        </div>

      <% end %>
    </div>

  <% end %>

  </div>
<!-- other users end -->



</div> <!-- row end -->